paths:
  raw:
    sid: 
    sedd:
    nvdrs: "data/raw/keyes_973_nvdrs_2023.csv"
    nvdrs_narratives: "data/raw/keyes_973_nvdrs_2023_narratives.csv"
    costal_counties: "data/raw/costal_counties_NOAA.csv" 
  processed:
    wonder_state: "data/processed/WONDER_state_99-24.csv"

#columns:
#  county_id: 
#  state_id: 
#  zip_id: 
#  date: 
#  outcome_attempts: 
#  outcome_deaths: 

#date_range:
#  start: 
#  end: 

#geographic_levels:
#  primary: 
#  secondary:
    